name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
    - master
jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Use pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build site
      run: sh ./build.sh
    - name: Commit and push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        git worktree add --detach .site
        cd .site
        git checkout --orphan gh-pages
        git rm --cached -rf .
        git clean -fd

        cp -R ../html/ .
        touch .nojekyll

        git add .
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit --allow-empty -m "Update site"
        mkdir -p ~/.ssh
        echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git remote rm origin
        git remote add origin git@github.com:${GITHUB_REPOSITORY}.git
        git push --force origin gh-pages

        cd ..
        git worktree remove .site
